package rest

const TRUST_PROXY = "TRUST_PROXY"
const VIEW_ENGINE = "VIEW_ENGINE"
const UPLOAD_DIR = "UPLOAD_DIR"
const MAX_UPLOAD_FILE_SIZE = "MAX_UPLOAD_FILE_SIZE"
const MAX_FIELD_SIZE = "MAX_UPLOAD_FILE_SIZE"
const MAX_FIELD_COUNT = "MAX_UPLOAD_FILE_SIZE"
const KEEP_EXTENSIONS = "KEEP_EXTENSIONS"
